# Generated by Django 5.2.4 on 2025-07-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudvideojuego',
            options={'verbose_name_plural': 'Solicitudes de Videojuegos'},
        ),
    ]
