# Generated by Django 5.2.4 on 2025-07-07 15:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0003_videojuego_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_salida', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='videojuego',
            name='desarrollador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='fecha_salida',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataformas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videojuegos', to='videojuegos.plataforma'),
        ),
    ]
