# Generated by Django 5.2.4 on 2025-07-07 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0004_plataforma_videojuego_desarrollador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='año_salida',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='año_salida',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
