# Generated by Django 5.2.4 on 2025-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0005_remove_plataforma_fecha_salida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='plataformas',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataformas',
            field=models.ManyToManyField(related_name='videojuegos', to='videojuegos.plataforma'),
        ),
    ]
