# Generated by Django 5.2.4 on 2025-07-07 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0006_remove_videojuego_plataformas_videojuego_plataformas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
