# Generated by Django 5.2.4 on 2025-07-07 19:22

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0008_alter_solicitudvideojuego_usuario_aprobador'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvideojuego',
            name='año_salida',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AddField(
            model_name='solicitudvideojuego',
            name='categorias',
            field=models.ManyToManyField(related_name='solicitudes', to='videojuegos.categoria'),
        ),
        migrations.AddField(
            model_name='solicitudvideojuego',
            name='desarrollador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvideojuego',
            name='fecha_solicitud',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='solicitudvideojuego',
            name='plataformas',
            field=models.ManyToManyField(related_name='solicitudes', to='videojuegos.plataforma'),
        ),
        migrations.AddField(
            model_name='solicitudvideojuego',
            name='portada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portada_solicitud_videojuego', to='videojuegos.captura'),
        ),
    ]
