# Generated by Django 5.2.4 on 2025-07-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0010_remove_solicitudvideojuego_portada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudvideojuego',
            old_name='usuario_aprobador',
            new_name='usuario_revisador',
        ),
    ]
